apiVersion: v1
entries:
  berichtservice:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-06-21T08:06:03.345022Z"
    description: De Berichtenservice faciliteert het versturen van berichten (bijvoorbeeld
      aan de hand van WRC sjablonen) en het rapporteren daarover. Hiervoor levert
      het zowel bulk-capaciteiten (voor bijvoorbeeld het versturen van mailings),
      als opvolg-capaciteiten (voor het controleren van bijvoorbeeld het aankomen
      van emails). Vooralsnog ondersteunt de Berichtenservice het versturen van mails
      en sms-berichten, maar er wordt nagedacht over het toevoegen van een post route
      en chatfunctionaliteit (social media). Het kan hierbij zowel zelfstandig opereren,
      als een front leveren voor functionaliteit van derden (Mailgun, Mailchimp, Messagbird,
      etc)
    digest: 4c9cf55fcdad20c79b7bf9f10984eb8fc69b8ecd07a53dbe7ad4625323e5079a
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: berichtservice
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - berichtservice-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2021-06-21T08:06:03.3497034Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
generated: "2021-06-21T08:06:03.3394021Z"
