apiVersion: v1
entries:
  bs:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-03T10:30:39.9013224Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 8e9712d38bbca284b2cb76135d2b84cf8fe3766559662a113e68cd77dd043af0
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bs
    urls:
    - bs-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2020-12-03T10:30:39.9142261Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
generated: "2020-12-03T10:30:39.8891384Z"
