apiVersion: v1
entries:
  bs:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-09-09T13:41:59.7120183Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 9cffccb52a948dcf8292aed3101b23920ae562ed3d2aaac149c115673cf7ec96
    home: pc.zaakonline.nl
    icon: pc.zaakonline.nl
    name: bs
    urls:
    - bs-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-09T13:41:59.6949816Z"
